Tweaked theme documentation to be more general to all modules and services instead of just the ones included by default and updated webserver config for the new WemX update (php8.1-fpm to php8.2-fpm).
WemXPro/documentation pull request #4
Opened 2023-12-24 14:45 UTC by thattheredstoner

2023-12-27 22:25 UTC, Mubeen142 commented
Hi @thattheredstoner 

Thank you for the pull request.

Could u revert the changes with the web server using php 8.2, that is no longer needed as in the new update wemx supports 8.1 just fine.

2023-12-28 08:05 UTC, thattheredstoner commented
Done

2024-02-05 16:31 UTC, PadowYT2 requested changes

2024-02-05 16:31 UTC, PadowYT2 commented on developers/themes.md
> +```
```suggestion
3. Duplicate all the default service and module folders, for example
- app/Services/Universal/Resources/views/client/tailwind `->` app/Services/Universal/Resources/views/client/material
- Modules/Affiliates/Resources/views/client/tailwind `->` Modules/Affiliates/Resources/views/client/material
```

2024-02-07 08:59 UTC, thattheredstoner commented
Tweaked theme.md to match requested change and added chmod files to installation.md

2024-02-07 10:33 UTC, PadowYT2 requested changes

2024-02-07 10:33 UTC, PadowYT2 commented on project/installation.md
> +
WemX installer already does chmod, also the command is invalid

2024-02-12 01:41 UTC, thattheredstoner commented
Reverted addition of that

2024-02-13 18:18 UTC, merged